sudo: required

cache:
  directories:
    - node_modules

language: node_js

node_js: 11

script:
  - npm test

deploy:
  provider: script
  script: curl -X POST https://hub.docker.com/api/build/v1/source/$DOCKER_USER_TOKEN/trigger/$DOCKER_HOOK_TOKEN/call/
  on:
    branch: master
